### ISSUE TITLE
Vulnerabilities

### ISSUE THREAD

**Issue by thiagoloureiro** [aksiksi/ncdmv#10]
Hi, not sure if you're interested in fixing vulnerabilities, here it goes:
<img width="1110" alt="image" src="https://github.com/user-attachments/assets/7e8524c7-9a2c-4a59-aa0c-dc3634c39f77">

**Comment by aksiksi** [comment]
Thanks for reporting. The Pipfile is only used for dev. The core application is in Go. So no security issues to worry about from this list.
