### ISSUE TITLE
Notifications to Discord not working

### ISSUE THREAD

**Issue by thiagoloureiro** [aksiksi/ncdmv#11]
Hi !
I pulled the latest and noticed the notifications stopped coming, tried to debug but no luck, when do you find time to check, please? I don't see any errors

**Comment by aksiksi** [comment]
Are you passing in env variables? I've changed the way the container works to support Docker Compose:

```
docker run --rm -v $(pwd):/config -e NCDMV_APPT_TYPE=permit -e NCDMV_LOCATIONS=cary,durham-east ghcr.io/aksiksi/ncdmv:latest
```

**Comment by thiagoloureiro** [comment]
> Are you passing in env variables? I've changed the way the container works to support Docker Compose:
> 
> 
> 
> ```
> 
> docker run --rm -v $(pwd):/config -e NCDMV_APPT_TYPE=permit -e NCDMV_LOCATIONS=cary,durham-east ghcr.io/aksiksi/ncdmv:latest
> 
> ```

Hey, I am not using on docker right now, using directly with go.

**Comment by aksiksi** [comment]
Can you share the full command you're using?

**Comment by thiagoloureiro** [comment]
Sure

I replaced the token of the discord but that's my command

`go run ./cmd/ncdmv --debug --appt-type driver-license  --locations=graham,roxboro,henderson,siler-city,sanford,erwin,smithfield -discord_webhook=https://discordapp.com/api/webhooks/1297352572016791612/x --database-path ./ncdmv.db`

and this is what I got

<img width="1116" alt="image" src="https://github.com/user-attachments/assets/002bf771-1886-4ef9-98cb-3ae818e0366e">

but nothing coming to discord, I've tested the webhook and works fine.

**Comment by aksiksi** [comment]
Interesting, it's working for me. Can you make sure you've pulled the latest commit?

```
time=2024-10-30T21:47:47.184-04:00 level=INFO msg="Setup logger" debug=false
time=2024-10-30T21:47:47.184-04:00 level=INFO msg="GPU support" disabled=false
time=2024-10-30T21:47:47.184-04:00 level=INFO msg="Loaded DB successfully"
time=2024-10-30T21:47:47.185-04:00 level=INFO msg="Enabled foreign key support"
time=2024-10-30T21:47:47.185-04:00 level=INFO msg="Running all up migrations..." databasePath=./ncdmv.db
time=2024-10-30T21:47:47.700-04:00 level=INFO msg="Initialized Chrome context" headless=false debug=false
time=2024-10-30T21:47:47.700-04:00 level=INFO msg="Created ncdmv client" webhook=true stopOnFailure=false notifyUnavailable=true
time=2024-10-30T21:47:47.700-04:00 level=INFO msg="Starting client" appt_type=permit locations=[ahoskie] timeout=5m0s interval=5m0s
time=2024-10-30T21:47:47.701-04:00 level=INFO msg="Listed existing appointments in provided locations" count=0
time=2024-10-30T21:47:47.701-04:00 level=INFO msg="Running for locations..." locations=[ahoskie] timeout=5m0s
time=2024-10-30T21:48:05.373-04:00 level=INFO msg="Found appointments in location" location=ahoskie num_appointments=108
time=2024-10-30T21:48:05.373-04:00 level=INFO msg="Done running for locations" locations=[ahoskie]
time=2024-10-30T21:48:05.431-04:00 level=INFO msg="Found appointments to update and notify" to_update=0 to_notify=108
time=2024-10-30T21:48:06.765-04:00 level=INFO msg="Sent notifications successfully" count=108
time=2024-10-30T21:48:06.765-04:00 level=INFO msg="Sleeping between location checks..." interval=5m0s
```

Found appointment change(s) at the following locations and times:

- **ahoskie**:
  - :white_check_mark: `2025-01-09 09:00:00 -0500 EST`
  - :white_check_mark: `2025-01-13 08:30:00 -0500 EST`
  - :white_check_mark: `2025-01-13 08:45:00 -0500 EST`
  - :white_check_mark: `2025-01-13 09:15:00 -0500 EST`
  - :white_check_mark: `2025-01-13 09:30:00 -0500 EST`
  - :white_check_mark: `2025-01-13 09:45:00 -0500 EST`
  - :white_check_mark: `2025-01-13 10:15:00 -0500 EST`
  - :white_check_mark: `2025-01-13 10:45:00 -0500 EST`
  - :white_check_mark: `2025-01-14 08:30:00 -0500 EST`
  - :white_check_mark: `2025-01-14 08:45:00 -0500 EST`
  - `(... more appointments available)`

Book an appointment here: https://skiptheline.ncdot.gov

**Comment by thiagoloureiro** [comment]
Hi, I found the issue

go run ./cmd/ncdmv -debug -l ahoskie -w webhook --database-path ./ncdmv.db


previously -> -discord_webhook now I've switched to "-w" and it worked.

thank you again!
