### ISSUE TITLE
Running on Docker Issue

### ISSUE THREAD

**Issue by thiagoloureiro** [aksiksi/ncdmv#4]
Hi! When I Run on docker I have the following error:

2024/10/20 01:30:34 INFO GPU support disabled=false
2024/10/20 01:30:34 INFO Loaded DB successfully
2024/10/20 01:30:34 Failed to enable foreign key support: unable to open database file: out of memory (14)

Then I tried to specify a db path like:
-database_path /tmp/ncdmv.db

Then I got the following error:

024/10/20 01:31:11 INFO Starting client appt_type=driver-license locations="[durham-south hillsborough raleigh-east raleigh-north ahoskie durham-east fuquay-varina garner raleigh-west cary clayton wendell]" timeout=2m0s interval=10m0s
2024/10/20 01:31:11 ERROR handleTick failed err="failed to delete appointments before current time (2024-10-20 01:31:11.832922292 +0000 UTC m=+1.063103752): SQL logic error: no such table: appointment (1)"
2024/10/20 01:31:11 INFO Sleeping between location checks... interval=10m0s

any ideas?

thanks for the app man! it's amazing!

**Comment by aksiksi** [comment]
Hello! Ah, it seems like I failed to include migrations & a volume when I setup the new Docker container build in 0f2d3b9e741b576693a9d4658483eae28af8a143.

You should now be able to run it like so (note the `/config` volume):

```
docker run --rm -v $(pwd):/config ghcr.io/aksiksi/ncdmv:latest -database_path=/config/ncdmv.db
```

I've also updated the README.

**Comment by thiagoloureiro** [comment]
hey, it seems I hit the same issue:

ncdmv % docker run --rm -v $(pwd):/config ghcr.io/aksiksi/ncdmv:latest -database_path=/config/ncdmv.db
WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested
2024/10/20 02:36:05 INFO GPU support disabled=false
2024/10/20 02:36:05 INFO Loaded DB successfully
2024/10/20 02:36:05 INFO Enabled foreign key support
2024/10/20 02:36:06 INFO Initialized Chrome context headless=true debug=false
2024/10/20 02:36:06 INFO Starting client appt_type=permit locations="[cary durham-east durham-south]" timeout=2m0s interval=30m0s
2024/10/20 02:36:06 ERROR handleTick failed err="failed to delete appointments before current time (2024-10-20 02:36:06.865547041 +0000 UTC m=+1.170581708): SQL logic error: no such table: appointment (1)"
2024/10/20 02:36:06 INFO Sleeping between location checks... interval=30m0s

**Comment by thiagoloureiro** [comment]
I checked the files and I found that: - maybe those files are from my local env.. just to be sure

<img width="1054" alt="image" src="https://github.com/user-attachments/assets/f0d0c6f5-7943-4ff4-a3e9-b11f42b7c3f6">

there are two db files, which one we should use ?

**Comment by aksiksi** [comment]
Ignore/delete the one under `database/`. The Docker command can be run from anywhere - does not need to run from source root.

You should use the one under the source directory specified in the volume (`pwd` in this case) - `$(pwd):/config`. 

Here is what I see - your output is missing the migrations log for some reason:

```
2024/10/20 02:40:00 INFO GPU support disabled=false
2024/10/20 02:40:00 INFO Loaded DB successfully
2024/10/20 02:40:00 INFO Enabled foreign key support
2024/10/20 02:40:00 INFO Running all up migrations... databasePath=/config/ncdmv.db
2024/10/20 02:40:01 INFO Initialized Chrome context headless=true debug=false
2024/10/20 02:40:01 INFO Starting client appt_type=permit locations="[cary durham-east durham-south]" timeout=2m0s interval=30m0s
2024/10/20 02:40:01 INFO Listed existing appointments in provided locations count=0
```

**Comment by aksiksi** [comment]
Actually, you may need to pull the new image first:

```
docker pull ghcr.io/aksiksi/ncdmv:latest
```

**Comment by thiagoloureiro** [comment]
you got it! Thanks a lot! Now I'll try to run it on my k8s cluster to keep it here and alert me when an appointment shows up :P

I just got an error with SSL but most probably something missing on the image with certs

2024/10/20 02:45:11 Failed to send message to Discord webhook "https://discordapp.com/api/webhooks//: failed to send message to Discord webhook: Post "https://discordapp.com/api/webhooks tls: failed to verify certificate: x509: certificate signed by unknown authority

perhaps missing ca-certs?

`RUN apt-get update && apt-get install -y ca-certificates`

**Comment by thiagoloureiro** [comment]
maybe this line should fix on the Dockerfile

`RUN apt-get update; apt-get upgrade -y; apt install dumb-init -y; apt install -y ca-certificates`

**Comment by aksiksi** [comment]
I currently don't use the Dockerfile to build the image - I use Nix instead. See: https://github.com/aksiksi/ncdmv/blob/main/flake.nix#L29

Latest image should now have certs added: https://github.com/aksiksi/ncdmv/commit/b4197063cd2ef36904e7484f82fb0e119dd05e7b#diff-206b9ce276ab5971a2489d75eb1b12999d4bf3843b7988cbe8d687cfde61dea0R36

**Comment by thiagoloureiro** [comment]
> I currently don't use the Dockerfile to build the image - I use Nix instead. See: https://github.com/aksiksi/ncdmv/blob/main/flake.nix#L29
> 
> Latest image should now have certs added: [b419706#diff-206b9ce276ab5971a2489d75eb1b12999d4bf3843b7988cbe8d687cfde61dea0R36](https://github.com/aksiksi/ncdmv/commit/b4197063cd2ef36904e7484f82fb0e119dd05e7b#diff-206b9ce276ab5971a2489d75eb1b12999d4bf3843b7988cbe8d687cfde61dea0R36)

thank you!!
